### ISSUE TITLE
Not Able to Deploy and Run in iPA file. 

### ISSUE THREAD

**Issue by dipakh** [appcelerator-archive/ti.paint#16]
HI Team,

I am not able to incorporate the module in Appcelerator iOS Project. When I incorporate and generate an iPA my iPA doesnt work . 

I have referenced the module as instructed. My Screen doesnt goes from List Screen to detail screen. I have referenced the module in the detail page of the project.

**Comment by hansemannn** [comment]
I cannot reproduce this issue while having the module in production-use. Please check your implementation before or file a JIRA for it. Thanks!
