### ISSUE TITLE
How to install this as a module

### ISSUE THREAD

**Issue by justingosan** [appcelerator-archive/ti.paint#18]
I stumbled here upon clicking the Download button from the Appcelerator marketplace. Normally, it should take me to the products page and allow me to download this as a zip file ready to be installed as a module. Can anyone give directions on how to compile this repo to that same zip file? Thanks

**Comment by ashcoding** [comment]
The binary/zip can be found in the releases page.
https://github.com/appcelerator-archive/ti.paint/releases

To be exact, here: https://github.com/appcelerator-archive/ti.paint/releases/download/android-2.0.3/ti.paint-android-2.0.3.zip

**Comment by justingosan** [comment]
Thanks for that! @ashcoding
