### ISSUE TITLE
1.4 and 1.4.1 still not working on iOS iPad Air

### ISSUE THREAD

**Issue by mattmol** [appcelerator-archive/ti.paint#7]
I have an app I inherited that uses ti.paint 1.1
When I upgrade to 1.4 (and even tried 1.4.1), the app opens on 64-bit, but the drawing and text addition features do not work at all.
It just draws a black line when I tap and drag with any of the tools.... but the line disappears completely on touch end.

Any thoughts?
Should I try to recompile the 1.1 version for 64 bit?  the 1.1 version still works on 32-bit... but the 1.4 version does NOT work on 32-bit.

**Comment by hansemannn** [comment]
The module works for me on both iOS and Android, running latest SDK- and module versions. Please check your implementation or file a JIRA-ticket, thanks!
