### ISSUE TITLE
Couldn't set strokeWidth in Android lollipop

### ISSUE THREAD

**Issue by kabeer-anubavam** [appcelerator-archive/ti.paint#8]
Hi, I am struck with this issue for couple of days. Please help me with the following code:

var paintView = Paint.createPaintView({
		image : icons.chartBoardBg,
		strokeColor : '#0f0',
		strokeAlpha : 255,
		strokeWidth : 10,
		eraseMode : false
	});
	win.add(paintView);

var buttonStrokeWidth = Ti.UI.createButton({
		left : 10,
		bottom : 10,
		right : 10,
		height : 50,
		title : 'Increase Stroke Width'
	});

	buttonStrokeWidth.addEventListener('click', function(e) {
		paintView.strokeWidth = 50;
	});
	win.add(buttonStrokeWidth);

After the button click I am trying to increase the strokeWidth of the paintView. But its not working and user is unable to draw.

**Comment by hansemannn** [comment]
Fixed in latest 2.0.4 version.
