### ISSUE TITLE
Crash when calling setStrokeWidth() while touch events are being processed

### ISSUE THREAD

**Issue by grebulon** [appcelerator-archive/ti.paint#9]
`setStrokeWidth` (and `color`/`mode`/`alpha` and also `setImage`) are called on the kroll runtime thread. All these lead to `UIPaintView.finalizePaths()` which nullifies `tiPaths`. If this happens while touch events are being processed (on the UI thread), you'd get a null reference in `finalizePath()` (without s).

The solution is to either execute all the public interface on the UI thread (same as `clear` is implemented), or synchronize on `tiPath` and possibly other members.

**Comment by hansemannn** [comment]
Fixed in latest 2.0.4 version.
